"""Add notes field to accounts

Revision ID: 70ccafdfb117
Revises: f09253b8f529
Create Date: 2026-09-11 13:08:57.592382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ccafdfb117'
down_revision: Union[str, Sequence[str], None] = 'f09253b8f529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'notes')
    # ### end Alembic commands ###
